### ISSUE TITLE
[Request] Documentation / How-to Guide

### ISSUE THREAD

**Issue by dannyhanes** [DirtyCajunRice/grafana-scripts#1]
Saw your post on Reddit, which prompted me to install Grafana. I am a complete Grafana noob, but do have Plex, Sonarr, Radarr etc already running. How do I go about getting that data to show up in Grafana? 

Thanks!

**Comment by d-hanes** [comment]
@DirtyCajunRice No worries, I appreciate it! :)

**Comment by driz** [comment]
@dannyhanes I've never used grafana before, but I added a pull request with some basic steps that I followed to get this setup and working. my CE device isn't an ASA, so i used telegraf to pull bandwidth stats directly from the plex server (along with disk stats from the fibre channel san). I didnt include the telegraf notes, but if you view the pull request for readme.md you should be able to get this working.

**Comment by DirtyCajunRice** [comment]
Added basic formatting to his post. Should cover you.
