### ISSUE TITLE
issue with new tautulli.py

### ISSUE THREAD

**Issue by drizuid** [DirtyCajunRice/grafana-scripts#10]
Hello, Long time user of your dashboard, great work! Initially, in preparation for the changes i modified tautulli.py to leverage ipstack after I got my api key. This worked fine, but you can only do 100 free lookups. After than, i pip3 installed geoip, get your updated tautulli.py and ran it. It works for everything except my map. 

I checked to see if you had made corresponding changes to the grafana json but I saw none. In lieu of logs (not sure which ones you'd want or where to get them) I hope the following data helps.

`SELECT count("location") AS "metric" FROM "Tautulli" WHERE ("type" = 'Session') AND time >= now() - 1m GROUP BY "region_code"`

which in my case returns:
```
name: Tautulli
tags: region_code=5000473
time                metric
----                ------
1531954365899092742 2
```
this data doesn't plot anything on the map for some reason though. 

If there is anything I can provide or do to assist tshooting, please let me know! Thanks!

**Comment by madbuda** [comment]
look like what is being returned now is geoname_id 
the worldmap plugin doesn't like this, it is not a lat/long or a geohash
