### ISSUE TITLE
Issues with scripts

### ISSUE THREAD

**Issue by digitalbydesign** [DirtyCajunRice/grafana-scripts#12]
After making necessary changes to the configuration.py script and attempting to run the tautulli.py script using 'python3 tautulli.py I get the following output:

`troy@grafana:/opt/plex/scripts$ python3 tautulli.py
Traceback (most recent call last):
  File "tautulli.py", line 54, in <module>
    geodata = GeoLite2db(sessions[session]['ip_address_public'])
  File "tautulli.py", line 31, in GeoLite2db
    os.rename(tempfullpath, dbfile)
NotADirectoryError: [Errno 20] Not a directory: 'GeoLite2-City.tar.gz/GeoLite2-City.mmdb' -> 'GeoLite2-City.mmdb'`

**Comment by samwiseg00** [comment]
Fixed this in the latest update. You can close this :)

**Comment by DirtyCajunRice** [comment]
closed
