### ISSUE TITLE
The address 172.17.0.1 is not in the database.

### ISSUE THREAD

**Issue by smanocchio** [DirtyCajunRice/grafana-scripts#17]
I recently noticed that my influxdb database stopped receiving data from tautulli.py.  When I try to run the script manually I receive this message:

Traceback (most recent call last):
  File "tautulli.py", line 59, in <module>
    geodata = GeoLite2db(sessions[session]['ip_address_public'])
  File "tautulli.py", line 36, in GeoLite2db
    geodata = reader.city(ipaddress)
  File "/usr/local/lib/python3.6/dist-packages/geoip2/database.py", line 114, in city
    return self._model_for(geoip2.models.City, 'City', ip_address)
  File "/usr/local/lib/python3.6/dist-packages/geoip2/database.py", line 195, in _model_for
    record = self._get(types, ip_address)
  File "/usr/local/lib/python3.6/dist-packages/geoip2/database.py", line 191, in _get
    "The address %s is not in the database." % ip_address)
geoip2.errors.AddressNotFoundError: The address 172.17.0.1 is not in the database.

I have found that this only occurs when a local stream is being played.  I do not use 172.X.X.X anywhere in my network.   If all streams are coming over the WAN the script runs as expected. When streaming on LAN plex shows that my server is "nearby"  and Tautulli shows the correct LAN address. 

There were Tautulli and Plex updates recently however I did not notice the issue until after both so I am not sure which update (if any) were installed when this issue started.

**Comment by samwiseg00** [comment]
Fixed in the nightly branch. Note there is a major data structure change that will require you to modify the current Online Users table. You can get the new beta table [here](https://github.com/DirtyCajunRice/grafana-scripts/blob/nightly/dashboard/beta_online_users_table.json).

**Comment by smanocchio** [comment]
Working perfect so far, thank you!
