### ISSUE TITLE
Support for Linux without ASA

### ISSUE THREAD

**Issue by 12nick12** [DirtyCajunRice/grafana-scripts#21]
I was curious if support for Linux without ASA could be supported?

**Comment by drizuid** [comment]
Linux without ASA is supported, but likely outside of the scope of this particular project. Check out telegraf which can feed into the influxdb you'll already be using if you're utilizing this project. It's what I use to pull metrics from my linux systems. Telegraf can also pull metrics from docker containers if you happen to use any AND there's even a windows version of telegraf :)

**Comment by 12nick12** [comment]
Perfect. Thanks a million
