### ISSUE TITLE
Missing dashboard

### ISSUE THREAD

**Issue by GugZi** [DirtyCajunRice/grafana-scripts#23]
This [dashboard](https://camo.githubusercontent.com/92aff9b739e4f7310e15aa2bf1fe8cf65360af0c/68747470733a2f2f692e696d6775722e636f6d2f617638653048502e706e67) is not in the dashboard [folder](https://github.com/DirtyCajunRice/grafana-scripts/tree/master/dashboard)

**Comment by samwiseg00** [comment]
The dashboard is not missing. There is a dashboard included as well as JSON files for other options.

**Comment by samwiseg00** [comment]
I added some more panel examples. The rest are dependent on your environment.

https://github.com/DirtyCajunRice/grafana-scripts/tree/nightly/dashboard/example_panels
