### ISSUE TITLE
Users Online not populating

### ISSUE THREAD

**Issue by nowireless4u** [DirtyCajunRice/grafana-scripts#24]
I imported the json for the users online and noticed it is not populating with the default values included within the json file. When I change the first select by to field(*) users populate the table. Here is a screenshot of what options I am presented with if I manually select the field() value.
<img width="224" alt="screen shot 2018-11-14 at 10 36 20 pm" src="https://user-images.githubusercontent.com/30940223/48528675-01d36080-e85e-11e8-9d44-01e3fdd5fbb7.png">

**Comment by samwiseg00** [comment]
Please see the the change log. You need to be using the beta table.
https://github.com/DirtyCajunRice/grafana-scripts/releases
