### ISSUE TITLE
Suggestion to include Speedtest-cli script for bandwidth metrics

### ISSUE THREAD

**Issue by n1nj4888** [DirtyCajunRice/grafana-scripts#27]
Hi There,

Just a suggestion but, would it be possible to include / merge the following speedtest-cli script into the dirtycajunrice grafana-scripts docker? 

https://github.com/barrycarey/Speedtest-for-InfluxDB-and-Grafana

I currently run this as a separate docker but it would be good to merge these into a single docker and remove the current Cisco ASA dependency for bandwidth statistics from the grafana-scripts docker?

Thanks!

**Comment by samwiseg00** [comment]
1) That is out of scope for this project. As this is centered around Plex and not testing your bandwidth. 
2) If you would like something included into the docker, You will want to open an issue with the docker maintainer. https://github.com/si0972/grafana-scripts-docker
3) Cisco ASA is not a dependency. It is there if you conveniently have that device.

**Comment by n1nj4888** [comment]
Thanks @samwiseg00 - Apologies, I should have raised this suggestion with the docker maintainer
