### ISSUE TITLE
Grafana dashboard json doesn't match format of readme screenshot?

### ISSUE THREAD

**Issue by n1nj4888** [DirtyCajunRice/grafana-scripts#28]
Is there a later version of the template grafana dashboard for this since the screenshot in the readme (https://github.com/DirtyCajunRice/grafana-scripts/blob/master/README.md) seems to include a few more metrics/graphs than the template json file in the dashboards folder?

**Comment by samwiseg00** [comment]
There are aditional panels in nightly. 
https://github.com/DirtyCajunRice/grafana-scripts/tree/nightly/dashboard/example_panels

**Comment by n1nj4888** [comment]
Thanks @samwiseg00 

Could the following JSON panels also be added to the nightly? These are in the sample screenshot but missing from the example_panels folder in nightly ...

Plex Web Threads
Websock msg /s
Total Data Transferred (Today)
Total Data Transferred (Month)
Plex - Total Stream/s
Plex - Transcode/s
Plex - Direct Play/s
Plex - Direct Stream/s
Plex - Sync

Thanks again for the awesome work on this!

**Comment by samwiseg00** [comment]
**Plex Web Threads ,Plex - Sync, Websock msg /s** <- These are available with Zabbix and these scripts https://github.com/samwiseg00/plex/tree/master/debug_stats_monitoring. We _may_ implement this at some point in this project. 

**Total Data Transferred (Today) , Total Data Transferred (Month)** <- This can be monitored at the OS level. There are many ways to get this data into grafana. Google is your friend. 

**Plex - Total Stream/s, Plex - Transcode/s, Plex - Direct Play/s, Plex - Direct Stream/s** <- This data is already pushed into influx. You can create a single stat with this information. 

Just change the field for each type
<img width="514" alt="2018-11-22_22-11-50 1" src="https://user-images.githubusercontent.com/2241731/48927414-af202700-eea3-11e8-9098-bbe56082ce1b.png">
