### ISSUE TITLE
Database Withou any scripts

### ISSUE THREAD

**Issue by CAVACO-PT** [DirtyCajunRice/grafana-scripts#29]
Hello @DirtyCajunRice  , thanks for you work with this 

im having a problem , wondering if you can help ... the influx db is empty , and nothing in coming from the scripts .... i have other docker containers that are working fine with influx db , incluing a docker for plex stats ... i have created a new DB called plex , and have re done all like you explain in the configuration . but still nothing in the Db, can u please see if im doing anyhting wrong , the logs only  have this :

![image](https://user-images.githubusercontent.com/9946471/48904821-925e0200-ee57-11e8-9325-73d00aaa2af2.png)

my config is this :

########################### INFLUXDB CONFIG ###########################
influxdb_url = 192.168.1.20
influxdb_port = 8086
influxdb_username =
influxdb_password =

############################ SONARR CONFIG ############################
sonarr_server_list =   [
    ('https://sonarr1.domain.tld', 'xxxxxxxxxxxxxxx', '1'),
    ('https://sonarr2.domain.tld', 'xxxxxxxxxxxxxxx', '2'),
    #('https://sonarr3.domain.tld', 'xxxxxxxxxxxxxxx', '3')
    ]
sonarr_influxdb_db_name = 'plex'

############################ RADARR CONFIG ############################
radarr_server_list =   [
    ('https://radarr1.domain.tld', 'xxxxxxxxxxxxxxx', '1'),
    ('https://radarr2.domain.tld', 'xxxxxxxxxxxxxxx', '2'),
    #('https://radarr3.domain.tld', 'xxxxxxxxxxxxxxx', '3')
    ]
radarr_influxdb_db_name = 'plex'

############################ OMBI CONFIG ##############################
ombi_url = 'https://ombi.domain.tld'
ombi_api_key = 'xxxxxxxxxxxxxxx'
ombi_influxdb_db_name = 'plex'

########################## TAUTULLI CONFIG ############################
tautulli_url = http://192.168.1.20:8181
tautulli_api_key = xxxxxxxxxxxxxx
tautulli_failback_ip = 192.168.1.20
tautulli_influxdb_db_name = plex
tautulli_verify_ssl = False

**Comment by samwiseg00** [comment]
Run the scripts manually from the command line and verify there are no errors. I would suggest you run one at a time and validate there is data being populated in the DB.
You must have something misconfigured.

**Comment by CAVACO-PT** [comment]
@samwiseg00 thanks for the help , i think have run the script right ... here is the error

![image](https://user-images.githubusercontent.com/9946471/48918535-22667080-ee85-11e8-8a51-0c8824aab4c6.png)

**Comment by CAVACO-PT** [comment]
Dont have any script configured yet .. .want to get this going fist ....

**Comment by CAVACO-PT** [comment]
it gives an error in the script in the first lines 

![image](https://user-images.githubusercontent.com/9946471/48918654-f13a7000-ee85-11e8-8cd5-4c5c3b3a2fd8.png)

**Comment by samwiseg00** [comment]
You need to run the script with `python3 tautulli.py`

You need to set the proper config in `configuration.py`

**Comment by CAVACO-PT** [comment]
![image](https://user-images.githubusercontent.com/9946471/48918701-47a7ae80-ee86-11e8-92b4-895ee026e88d.png)

**Comment by samwiseg00** [comment]
You removed the quotes. Please refer to the example and only replace what _is inside_ the quotes

**Comment by CAVACO-PT** [comment]
@samwiseg00  thank you so much .. .really tought the '' where to remove ... its working know ... sorry for all the trouble . and thanks for the help again

**Comment by samwiseg00** [comment]
No problem
